package rules.isin;

import com.pojo.Person;
import com.pojo.School;

rule "in的复合使用"
    when
        $s: School($cn: className)
        $p: Person(className in ("五班", "六班", $cn))
    then
        System.out.println("check in的复合使用: " + $s + "," + $p);
end

rule "not in的复合使用"
    when
        $s: School($cn: className)
        $p: Person(className not in ("五班", "六班", $cn))
    then
        System.out.println("check in的复合使用: " + $s + "," + $p);
end