package rules;

import com.pojo.Person;

rule "test001"
    when
    then
        System.out.println("Hello world");
end


rule "test002"
    when
        $p : Person()
    then
        System.out.println("Hello world " + $p);
end


rule "test003"
    when
        $p : Person(name=="张三", age==30);
    then
        System.out.println("this is zhangsan:" + $p);
end


rule "test004"
    when
        $p : Person(name=="张三", age==30);
    then
        $p.setAge(40);
        // 触发其他规则
        update($p);
        System.out.println("zhangsan change age to 40 :" + $p);
end


rule "test005"
    when
        $p : Person(name=="张三", age==40);
    then
        System.out.println("zhangsan age is 40 :" + $p);
end


rule "test006"
    when
        $p : Person(age/2 ==20);
    then
        System.out.println("test006 execute");
end


rule "test007"
    when
        $p : Person((age%2) ==0);
    then
        System.out.println("test007 execute");
end